### ISSUE TITLE
Dependency conflict cause "InjectionManagerFactory not found"

### ISSUE THREAD

**Issue by Linary** [hugegraph/hugegraph-common#9]
```
Exception in thread "main" com.baidu.hugegraph.rest.ClientException: Failed to do request
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:69)
	at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:147)
	at com.baidu.hugegraph.api.version.VersionAPI.get(VersionAPI.java:41)
	at com.baidu.hugegraph.driver.VersionManager.getApiVersion(VersionManager.java:45)
	at com.baidu.hugegraph.driver.HugeClient.checkServerApiVersion(HugeClient.java:98)
	at com.baidu.hugegraph.driver.HugeClient.initManagers(HugeClient.java:84)
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:59)
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:48)
	at com.ikang.cc.grape.GrapeMain.main(GrapeMain.java:21)
Caused by: java.lang.IllegalStateException: InjectionManagerFactory not found.
	at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:98)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:98)
	at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:68)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:432)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
	at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
	at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:419)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:319)
	at com.baidu.hugegraph.rest.RestClient.lambda$get$2(RestClient.java:148)
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:67)
	... 8 more
```

**Comment by Linary** [comment]
https://github.com/hugegraph/hugegraph-client/issues/27
